import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { verifyAuth } from '@/lib/auth'
import { IcRoundLogout } from '@/components/svg/logout'
import { logout } from '@/actions/auth-actions'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Casetify Copy Site',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { user } = await verifyAuth()

  const RightSideArea = () => {
    if (user) {
      return (
        <div className="flex">
          <form className="flex" action={logout}>
            <Button>
              <IcRoundLogout />
              登出
            </Button>
          </form>
        </div>
      )
    }

    return (
      <div className="flex gap-[10px]">
        <Link href="/sso?mode=login">
          <Button variant="ghost">登陆</Button>
        </Link>
        <Link href="/sso?mode=register">
          <Button>注册</Button>
        </Link>
      </div>
    )
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="absolute text-[28px] z-10 text-black px-[16px] md:px-[32px] py-[12px] flex justify-between w-full items-center leading-[22px]">
          <div className="h-[40px]">
            <Link href="/">
              <Image
                src="/first/casetify-logo.png"
                alt="site-logo"
                width={120}
                height={40}
              />
            </Link>
          </div>

          <RightSideArea />
        </nav>
        {children}
      </body>
    </html>
  )
}
