import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { verifyAuth } from '@/lib/auth'
import LogoutBtn from '@/components/logout-btn'
import LayoutNav from '@/components/layout-nav'
import CartDrawer from '@/components/cart-drawer'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Casetify Copy Site',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { user } = await verifyAuth()

  const RightSideArea = () => {
    if (user) {
      return (
        <div className="flex gap-1">
          <Link href="/dashboard">
            <Button variant="ghost">控制台</Button>
          </Link>
          <LogoutBtn />
        </div>
      )
    }

    return (
      <div className="flex gap-1">
        <Link href="/sso?mode=login">
          <Button variant="ghost">登陆</Button>
        </Link>
        <Link href="/sso?mode=register">
          <Button>注册</Button>
        </Link>
        <CartDrawer />
      </div>
    )
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutNav>
          <div className="h-[40px]">
            <Link href="/">
              <Image
                src="/first/casetify-logo.png"
                alt="site-logo"
                width={120}
                height={40}
              />
            </Link>
          </div>

          <RightSideArea />
        </LayoutNav>
        {children}
      </body>
    </html>
  )
}
