import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { IcTwotoneSearch } from '@/components/svg/search'
import Image from 'next/image'
import { IcBaselinePerson } from '@/components/svg/login-person'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Casetify Copy Site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="absolute text-[28px] z-10 text-black px-[16px] md:px-[32px] py-[12px] flex justify-between w-full items-center leading-[22px]">
          <IcTwotoneSearch className="cursor-not-allowed" />

          <div className="relative h-[40px]">
            <Image
              src="/first/casetify-logo.png"
              alt="site-logo"
              width={120}
              height={40}
            />
          </div>

          <Link href="/sign-in">
            <IcBaselinePerson className="cursor-pointer" />
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
